### PR TITLE
Restructured Console application to use the DI, just like ASP.Net

### PR DESCRIPTION
**Pull request by P-Storm**
Hi,

Here another pullrequest. This is restructuring the project so that the DI is better. This information is a bit hidden, so I have changed it so that it is using the template.

What are the changes:

1. Changed loggin to the [default .net core logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1). Default it changes the console a small bit, add a timestamp for every message. How to use futher: see `ILogger<TwitchChatBot> _logger` for an example or use the documentation.
2. Use of an `IHostedService`. This is the recommended way to run your application with DI, see [this link](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1). This is so that you can use control-c in the console to cancel. You can use the `CancellationToken` to check for cancellation. It is injecting this for you on line Program.cs#55.

Note: my other pull request #1 isn't integrated in this one, but that should merge with no problems :) . The scan should be added in `Program.ConfigureService`.

### CODE REVIEW

**Comment by SiliconOrchid** [comment]
Hey @P-Storm, thank you very much for taking the time to produce this PR (and PR  #2)  - I can see plenty of effort has gone in here.
   
I think rather than just accepting it now, we would do it better justice to it, to work our way through it together on our next Twitch Stream (22 Jul 2020 @ 17:30 BST).

**Comment by P-Storm** [comment]
Hi @SiliconOrchid, I have mailed you with some details :).

**Review by SiliconOrchid — APPROVED** [review]
Ship it!

**Review by SiliconOrchid — APPROVED** [review]

**Comment by SiliconOrchid** [comment]
Hi have resolved merge conflicts and adopted the  changes provided.  Very useful and tidy.  Thank you.

**Pull request closed without merging**
